[project]
name = "jreview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.3",
    "sentencepiece>=0.2.1",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "torchaudio==2.8.0",
    "konlpy>=0.6.0",
    "dotenv>=0.9.9",
    "google-genai>=2.8.0",
    "transformers==4.48.3",
    "pymysql>=1.2.0",
    "tokenizer>=3.6.2",
    "flask>=3.1.3",
    "chromadb>=1.5.9",
    "openai>=2.41.1",
]
