-- STORE(업체 상세 정보 )
CREATE TABLE STORE (
    STORE_CODE VARCHAR(30) PRIMARY KEY UNIQUE,
    STORE_NAME VARCHAR(255),
    ADDRESS_DO VARCHAR(255),
    ADDRESS_JI VARCHAR(30),
    PHONE VARCHAR(30),
    BUSINESS_HOURS TEXT,
    PARKING VARCHAR(30),
    AMENITY VARCHAR(255),
    LAT DECIMAL(10,7),
    LNG DECIMAL(11,7),
    CATEGORY VARCHAR(30),
    STAR FLOAT,
    STORE_IMAGE_URL TEXT,
    AREA VARCHAR(30),
    PN_RATE FLOAT,
    AI_REPORT TEXT
);

-- MENU (메뉴 상세 정보)
CREATE TABLE MENU (
    MENU_CODE INT AUTO_INCREMENT PRIMARY KEY,
    STORE_CODE VARCHAR(30),
    MENU_NAME VARCHAR(255),
    MENU_PRICE INT,
    CNT INT,
    BEST BOOLEAN,
    FOREIGN KEY (STORE_CODE) REFERENCES STORE(STORE_CODE)
);


-- REVIEW (방문자 리뷰와 블로그 리뷰들의 정제 결과 통합 저장)
CREATE TABLE REVIEW (
    REVIEW_CODE INT AUTO_INCREMENT PRIMARY KEY,
    STORE_CODE VARCHAR(30),
    CONTENT TEXT,
    WRITTEN_DT DATE,
    YEAR INT,
    MONTH INT,
    DAY INT,
    REVIEW_PN CHAR(1),
    PN_SCORE FLOAT,
    FOREIGN KEY (STORE_CODE) REFERENCES STORE(STORE_CODE)
);

-- WORD (단어 상세 테이블)
CREATE TABLE WORD (
    WORD_CODE INT AUTO_INCREMENT PRIMARY KEY,
    REVIEW_CODE INT,
    WORD VARCHAR(30),
    WORD_PN CHAR(1),
    FOREIGN KEY (REVIEW_CODE) REFERENCES REVIEW(REVIEW_CODE)
);